version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
      - default
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: cryptodb
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
    ports:
      - "5632:5432"
    volumes:
      - /var/lib/postgres
    networks:
      - default

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - default

volumes:
  redis_data:

networks:
  default:
    driver: bridge